---
- name: Include installation tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include configuration tasks
  include_tasks: configure.yml

- name: Make sure service is started and enabled
  service:
    name: unbound
    state: started
    enabled: yes
